name: wechat_picker_library
description: "A foundation library for wechat_*_picker, provides extensions, themes, and widgets."
version: 1.0.5
topics:
  - picker
  - wechat

repository: https://github.com/fluttercandies/flutter_wechat_picker_library
issue_tracker: https://github.com/fluttercandies/flutter_wechat_picker_library/issues

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  photo_manager: ^3.0.0

dev_dependencies:
  flutter_lints: any
  flutter_localizations:
    sdk: flutter
