name: agelapse
description: A powerful tool for creating stabilized aging timelapses.
publish_to: 'none'

version: 1.5.1+26

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  apple_vision_face: ^0.0.4
  archive: ^4.0.7
  async_zip: ^0.1.0
  camera: ^0.11.0
  camera_android_camerax: 0.6.7
  camera_macos: ^0.0.9
  chewie: ^1.12.1
  cupertino_icons: ^1.0.8
  desktop_drop: ^0.6.1
  exif: ^3.3.0
  face_detector_plugin: ^0.0.3
  face_detection_tflite:
    git:
      url: https://github.com/hugocornellier/face_detection_tflite.git
      ref: 2b0992f5c24be7447ba84d29489b141631397e48
  ffmpeg_kit_flutter_new: ^2.0.0
  file_picker: ^10.3.2
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_email_sender: ^7.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.4.0
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.0
  flutter_timezone: ^4.1.1
  font_awesome_flutter: ^10.10.0
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_pose_detection: ^0.14.0
  heif_converter: ^1.0.1
  image: ^4.5.4
  image_picker: ^1.2.0
  intl: ^0.20.2
  material_symbols_icons: ^4.2858.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5
  saver_gallery: ^4.0.1
  sensors_plus: ^6.1.2
  share_plus: ^11.1.0
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.2
  tflite_flutter: ^0.11.0
  url_launcher: ^6.3.2
  vibration: ^3.1.3
  video_player: ^2.10.0
  video_player_win: ^3.2.0
  wakelock_plus: ^1.3.2
  wechat_assets_picker: ^9.8.0
  window_manager: ^0.5.1
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  fonts:
    - family: CedarvilleCursive
      fonts:
        - asset: fonts/CedarvilleCursive-Regular.ttf
  uses-material-design: true

  assets:
    - assets/images/
    - assets/ghost-custom.svg
    - assets/relax.svg
    - assets/models/face_detection_front.tflite
    - assets/models/face_detection_back.tflite
    - assets/models/face_detection_short_range.tflite
    - assets/models/face_detection_full_range.tflite
    - assets/models/face_detection_full_range_sparse.tflite
    - assets/models/face_landmark.tflite
    - assets/models/iris_landmark.tflite
    - assets/ffmpeg/windows/ffmpeg.exe
    - assets/ffmpeg/windows/LICENSE.txt

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"

flutter_native_splash:
  color: "#2b2b2b"
  image: assets/images/splash/logo.png
  android_12:
    color: "#2b2b2b"
    image: assets/images/splash/logo-android.png

